### ISSUE TITLE
Batch synchronization merges only changes of first file

### ISSUE THREAD

**Issue by tthuem** [tthuem/VariantSync#21]

**Comment by Kogoro** [comment]
Batch synchronization merges only first changes. Also only marks the classes as merged and not the changes and changed code fragments, so the sync list is not empty but throws an error.
![unbenannt](https://user-images.githubusercontent.com/8019776/27604729-79cbbe2e-5b7a-11e7-935e-dec7a03d4971.PNG)
```
java.lang.NullPointerException
	at java.util.ArrayList.<init>(Unknown Source)
	at de.ovgu.variantsync.applicationlayer.merging.MergeOperationProvider.checkConflict(MergeOperationProvider.java:33)
	at de.ovgu.variantsync.applicationlayer.context.ContextProvider.getAutoSyncTargets(ContextProvider.java:362)
	at de.ovgu.variantsync.ui.controller.ContextController.getAutoSyncTargets(ContextController.java:171)
	at de.ovgu.variantsync.ui.view.mergeprocess.SynchronizationView.refreshSyncTargets(SynchronizationView.java:109)
	at de.ovgu.variantsync.ui.view.mergeprocess.SynchronizationView.processChangeSelection(SynchronizationView.java:205)
	at de.ovgu.variantsync.ui.view.mergeprocess.SourceFocusedView$6.widgetSelected(SourceFocusedView.java:207)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```
